Environment=GitHub Actions
Base.URL=https://courseapi-dev-c8bbhca5b6dwfag9.centralindia-01.azurewebsites.net/api
Browser=API Testing
Platform=Ubuntu Latest
Node.Version=18.x
Test.Framework=Playwright
Reporter=Allure
