// Configuration for Skolasti API
// Supports environment variables for CI/CD
module.exports = {
  baseURL: process.env.API_BASE_URL || "https://webapi-dev-g6bwgkg6d2hcdrb2.centralindia-01.azurewebsites.net/api",
  CoursebaseURL: process.env.COURSE_API_BASE_URL || "https://courseapi-dev-c8bbhca5b6dwfag9.centralindia-01.azurewebsites.net/api",
  headers: {
    "Authorization": process.env.API_TOKEN || "bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImd0eSI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwia2lkIjoiRC1CMGFzUXk2OFV2a3M0QkR0QWRjUWJ0MmtzIn0.eyJhdWQiOiJhNTBjZDdkZC1mNmFkLTQ0NzAtODkwMC1hMzhlMzQ1NjFkOTUiLCJleHAiOjE3NjUxMzE5MTIsImlhdCI6MTc2NTEyODMxMiwiaXNzIjoiaHR0cHM6Ly9hdXRoLnNrb2xhc3RpLmNvbS8iLCJzdWIiOiJmNzEwM2RhNi1mYzdhLTRjZmQtODgwYi04OTYxNmU2ZGVlZWEiLCJqdGkiOiJmYzU5ODIxYi00MDA5LTQyZGMtYjJiMy1kMDhiOTRlNGYxOTEiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoic2lyaXNoYS5iQGlub3Zhci10ZWNoLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhcHBsaWNhdGlvbklkIjoiYTUwY2Q3ZGQtZjZhZC00NDcwLTg5MDAtYTM4ZTM0NTYxZDk1Iiwic2NvcGUiOiJvcGVuaWQgb2ZmbGluZV9hY2Nlc3MiLCJyb2xlcyI6WyJ1c2VyIl0sInNpZCI6ImZmODg2ZGMzLTU0NTItNGIxNy05MzM2LWI3YWUxMWE5NDI4YiIsImF1dGhfdGltZSI6MTc2NTEyODMxMiwidGlkIjoiZjI2ZmExMmQtNjUyZi00NTI4LTg3M2ItYWEyZGM0OWU2MTU3In0.bkILGefdNom9uD9ihd29BHrXvKMAgaCoGeqZYQKsTB89g_eDl7otF3H5cf34-GP6HZ5mJLXPgtzNyNkWT9MBcjlHwvYIblhNMUbTj4w13crlG84jYKUJfTkI3AxQezIZFfncbwIv3hVL8FHCb5Th4f67Dta0cdVWZTkMRDV_NoSS-edtsuyKS0VBP4I5dg3uCfDa03qQEQDGJCvdph6Kj8Os6c1TQTyhbBSpBSpYTAkRjWL5P-98yJajdM6wrdBICFElYyz4fh7gS3Yjbe7NwONcmYO1CUaHydIQi5lHhmXrJ8PPQRtgkB_vmELhWzJ5TFq01RiV3Wbtw_b6YH7ivg",
    "Content-Type": "application/json"
  }
};
