// Configuration for Skolasti API
// Supports environment variables for CI/CD
module.exports = {
  baseURL: process.env.API_BASE_URL || "https://webapi-dev-g6bwgkg6d2hcdrb2.centralindia-01.azurewebsites.net/api",
  CoursebaseURL: process.env.COURSE_API_BASE_URL || "https://courseapi-dev-c8bbhca5b6dwfag9.centralindia-01.azurewebsites.net/api",
  headers: {
    "Authorization": process.env.API_TOKEN ? `Bearer ${process.env.API_TOKEN}` : "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImd0eSI6WyJhdXRob3JpemF0aW9uX2NvZGUiXSwia2lkIjoiRC1CMGFzUXk2OFV2a3M0QkR0QWRjUWJ0MmtzIn0.eyJhdWQiOiJhNTBjZDdkZC1mNmFkLTQ0NzAtODkwMC1hMzhlMzQ1NjFkOTUiLCJleHAiOjE3NjUxMzY2MzksImlhdCI6MTc2NTEzMzAzOSwiaXNzIjoiaHR0cHM6Ly9hdXRoLnNrb2xhc3RpLmNvbS8iLCJzdWIiOiJmNzEwM2RhNi1mYzdhLTRjZmQtODgwYi04OTYxNmU2ZGVlZWEiLCJqdGkiOiI5MDdmNjJmZi1lZjBlLTQ2ZjAtYmQwOC0xYmI0NWFhZjk1MDYiLCJhdXRoZW50aWNhdGlvblR5cGUiOiJQQVNTV09SRCIsImVtYWlsIjoic2lyaXNoYS5iQGlub3Zhci10ZWNoLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJhcHBsaWNhdGlvbklkIjoiYTUwY2Q3ZGQtZjZhZC00NDcwLTg5MDAtYTM4ZTM0NTYxZDk1Iiwic2NvcGUiOiJvcGVuaWQgb2ZmbGluZV9hY2Nlc3MiLCJyb2xlcyI6WyJ1c2VyIl0sInNpZCI6IjNhZGY0M2RkLTk1MTctNGZmOC04NmI0LTRiNTkzYTljYTE0YyIsImF1dGhfdGltZSI6MTc2NTEzMzAzOSwidGlkIjoiZjI2ZmExMmQtNjUyZi00NTI4LTg3M2ItYWEyZGM0OWU2MTU3In0.eeDmkJ3HXkTCyzy9xW6Ri6A77bz5qc24pzAzW1gcFUjZ_JL1d3cgMnJbYyw68Tlhf1Z0uV31FK3R-RUG_5SjNybbAKJLOeTCp_XObUPOP5tiVTEtM2WOZ8EVSWtPqeamSxn_BZMaVR4l5CYN-f3Kv1LCPxcnFIujyW8zmupVyO0QHYMIRCTRfWPBSCWPAJwkdyHfpq4OFUn4K7rHB8UdOowNYBWXAvnqgPqAoGcGJVQ-NaqZiinp9zAFefN29O5aNTCdySpsKJOjTC2xUHiLxTdAAOstZ74gFAziPZc_q858Mm2BD1QaU5kItupihgyeSv2V-WYhuMA6mJzALNyShg",
    "Content-Type": "application/json"
  }
};
